### ISSUE TITLE
Corrupted SLSTR scenes

### ISSUE THREAD

**Issue by BaptisteVandecrux** [wehrad/SICE#13]
BT_S7 in 2018 doy 74:

![image](https://user-images.githubusercontent.com/35140661/105173323-2489ef80-5b21-11eb-979f-683f343d2471.png)

Zoomed in:
![image](https://user-images.githubusercontent.com/35140661/105173973-1a1c2580-5b22-11eb-919a-9f0b9c6801da.png)

I expect these corrupted scenes to be responsible for strange cloud masks I've seen in the last SICE output:
![image](https://user-images.githubusercontent.com/35140661/105173894-fce75700-5b21-11eb-8ea1-35cdd073886f.png)

**Comment by wehrad** [comment]
At the moment I run SICE from DOY 121 to 273 and therefore have not seen those corrupted files, thank you! Is that the only date you detected? Maybe it has something to do with the time of the year: DOY 74, March 15th, is very early in the season.

**Comment by BaptisteVandecrux** [comment]
Posted on STEP:
https://forum.step.esa.int/t/gpt-outputs-geotiff-with-corrupted-bands-after-bandextract/27888

**Comment by BaptisteVandecrux** [comment]
This was caused by a change of the BandSelect output format in SNAP8.
It is solved in https://github.com/GEUS-SICE/SICE/tree/SNAP8 by using "Subset" instead.
Note that PPGC do not work in SNAP8 at the moment so it relies on TPGC.
