### ISSUE TITLE
Looking for SLSTR scene the next minute when it should be the minute before

### ISSUE THREAD

**Issue by BaptisteVandecrux** [wehrad/SICE#14]
If I understand it well, S3_proc is looking for a SLSTR scene that is either taken at the same minute (variable olci_time) or one minute **after** (variable olci_time1) the OLCI acquisition:

```
  olci_time=${olci_dts:9:4}
  olci_time1=$(date -d "${olci_date} ${olci_time} + 1 minute" "+%H%M")
  fileroot="S3._SL_1_RBT____........T" # grep for acquisition not ingest time
  # pick first nearby slstr
  slstr_folder=$(ls ${inpath} | grep -E "${fileroot}${olci_time}|${fileroot}${olci_time1}" |head -n1 || true)
```

But when I try the test case, the SLSTR scenes are either acquired at the same or at the **previous** minute relative to the OLCI acquisition:

![image](https://user-images.githubusercontent.com/35140661/105175257-f78b0c00-5b23-11eb-9e7d-3a6c89d79e67.png)

I have modified my version of S3_proc.sh to look for SLSTR scenes also on that previous minute:
```
  olci_time=${olci_dts:9:4}
  olci_time1=$(date -d "${olci_date} ${olci_time} + 1 minute" "+%H%M") 
  olci_time2=$(date -d "${olci_date} ${olci_time} - 1 minute" "+%H%M")
  fileroot="S3._SL_1_RBT____........T" # grep for acquisition not ingest time
  # pick first nearby slstr
  slstr_folder=$(ls ${inpath} | grep -E "${fileroot}${olci_time}|${fileroot}${olci_time1}|${fileroot}${olci_time2}" |head -n1 || true)
```

**Comment by wehrad** [comment]
That would be very interesting to have @mankoff thoughts on that issue! Thank you in advance Ken!

**Comment by mankoff** [comment]
If SLSTR acquires before OLCI, then the code change looks good (I haven't tested it).
