### ISSUE TITLE
Folders larger than 10Gb ignored although containing data to process

### ISSUE THREAD

**Issue by BaptisteVandecrux** [wehrad/SICE#15]
If I understand it well, the following lines of S3_proc.sh test if the output of gpt is <10Gb. If not it removes the folder.
```
  # # Discard out bad folders (defined as size > 10 GB)
  (cd ${dest}/../; du -sm * | awk '$1 > 10000 {print $2}' | xargs rm -fr)
  if [[ ! -d "${dest}" ]]; then continue; fi # if we removed the directory, break out of the loop
```

In my case the folder do contain date. So why this folder should be ignored?

![image](https://user-images.githubusercontent.com/35140661/105184897-2e671f00-5b30-11eb-9409-35e23affeba9.png)

**Comment by wehrad** [comment]
What are the SICE options you set to obtain those outputs? Your files are really heavy, I usually never have files over 3Mo for Greenland (masked for clouds, but still!).

**Comment by BaptisteVandecrux** [comment]
This was due to a change of BandSelect output in SNAP8: masks were saved in the geotiff file as well.
In https://github.com/GEUS-SICE/SICE/tree/SNAP8 Subset is used instead.
Unfortunately per-pixel geocoding does not work in SNAP8, so it uses tie point geocoding.
