### ISSUE TITLE
exclude outputting albedo_spectral_planar and albedo_spectral_spherical for oxygen bands 12,13,14,15

### ISSUE THREAD

**Issue by jasonebox** [wehrad/SICE#16]
no point in having SICE output for these bands.

**Comment by wehrad** [comment]
This is actually already the case (writing outputs with a loop from 0 to 10, then 15 to 21 corresponding to channels 1 to 11 and 16 to 21).

https://github.com/AdrienWehrle/SICE/blob/eb7d3b5315e023f6354757b0b2c25c7df3721ffc/sice.py#L371-L379
