### ISSUE TITLE
SICE_deliverables/FransJosefLand 2018

### ISSUE THREAD

**Issue by jasonebox** [wehrad/SICE#27]
at BC, no FransJosefLand 2018 in SICE_deliverables/FransJosefLand/

are the data at PTEP?

**Comment by wehrad** [comment]
Yes they are, I have to bring everything from my hard drive to BC!

**Comment by jasonebox** [comment]
July 2018 has few cases unlike July 2019, see images below... may be 2018 July is just more cloudy or has a different cloud ID?
![image](https://user-images.githubusercontent.com/32133350/109835911-efa2a980-7c43-11eb-8913-05210cbb71ed.png)
![image](https://user-images.githubusercontent.com/32133350/109835952-fb8e6b80-7c43-11eb-931f-4f1760adcf76.png)
