### ISSUE TITLE
Need to provide flag for cloud instead of removing cloudy pixels 

### ISSUE THREAD

**Issue by BaptisteVandecrux** [wehrad/SICE#7]
Because:
1) cloud detection still very unstable:
![billede](https://user-images.githubusercontent.com/35140661/98468630-a5507500-21db-11eb-9068-fc37caf836b8.png)

2) bands such as "diagnostic_retrieval" are useful even in presence of clouds. 

I guess it should be done about here:
https://github.com/AdrienWehrle/SICE/blob/master/dm.grass.sh#L64-L68

Or did I miss the motivation behind removing cloudy pixels?

**Comment by jasonebox** [comment]
I agree this is a v useful improvement to make

**Comment by jasonebox** [comment]
the cloud buffering is what makes the circular gaps... suggest reducing the buffer radius or probably better is to turn it off

**Comment by wehrad** [comment]
I agree and will work on it. There could be two cloud masks: the original one and the one with cloud buffering.
